{% set name = "kramdown" %}
{% set version = "2.1.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 089956b32ef77cf85136553b392635d9e2b8b6c7bd8e470db6a9a1be172088b6

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/COPYING
  summary: kramdown is yet-another-markdown-parser

  doc_url: http://kramdown.gettalong.org/rdoc
  dev_url: http://github.com/gettalong/{{ name }}

extra:
  recipe-maintainers:
    - sodre
