{% set name = "kramdown" %}
{% set version = "2.5.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 87bbb6abd9d3cebe4fc1f33e367c392b4500e6f8fa19dd61c0972cf4afe7368c

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >2.5
  run:
    - ruby >2.5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/COPYING
  summary: kramdown is yet-another-markdown-parser

  doc_url: http://kramdown.gettalong.org/rdoc
  dev_url: http://github.com/gettalong/{{ name }}

extra:
  recipe-maintainers:
    - sodre
