{% set name = "kramdown" %}
{% set version = "2.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: ce24100c836ff4bae05f2d88b6d6022c978d62e6a1c33a0211abcd788e73a441

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/COPYING
  summary: kramdown is yet-another-markdown-parser

  doc_url: http://kramdown.gettalong.org/rdoc
  dev_url: http://github.com/gettalong/{{ name }}

extra:
  recipe-maintainers:
    - sodre
