travis:
  secure:
    BINSTAR_TOKEN: coXtXrSh9aUNxXaSetyF/D0tfQWZC20y3Ck3GQ8rw0FZJ4FX3PuWTCHirjvaEQ9Ho2OXHlPC7ze+kNEhQu3cfImi2WhcCrm4WHepfJutcrEu/QSBHu5whzKtDFzymuoGhfi5p2smLxxZPHETyqCRbapGCs74/MriQxl/SLXq2UoEVc+q7Kq2pJpBTM7gNEbfy8hFUPX8cdM9pXITWQMWs3vqR8r0e5XU+AWF7pjoeCotQF4u3Zfp8S+TMVWxrhTAgXeNRVlsTAF8q3mFML7r1GU8BaWP/FIIGzP3BytccHn/HnqZgdjUBE4GRk2rFOk/dyc05k0M6vLl+TKLJ8qEqLSeuEcPQQy+f8wT5L52JrduubuRGhuTd0gO7bPb/C6yU7QDdd3zXoK3yQUuATmip7LOdOq1z0DRWMYsgtVYmr3/Bn8x8HQjP5DgNcCRnWgIQWKVEGvrCknIyoIQcJDRQBXDyDT7grGgFQkwEvBFPa8EsubeaOqSiC2vwmwX9Y4YWC0b1ZWUP9BHmN4GwQ388EA914nD0JctMU5SGX9FbBAOyz4mPNQO4NE7BW2HSS1LnjEsmObYKjtviXLSADegKS5NPO6zsjE9gu/DGv4CESHnw845/ybCmtPJdd+yx8XAKvJjvqkt+E8Vz/EcWRSvGL+va3B25p0Ugi/kkaT4D9I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
